version: "3.6"

services:
  mongodb:
    image: "mongo"
    

  server:
    build: 
      context: ./backend
    depends_on:
      - mongodb
    environment:
      - DB=mongodb://mongodb:27017/mestodb
    ports:
      - 5000:3000

  frontend:
    build: 
      context: ./frontend
    depends_on: 
      - server
    ports:
      - 80:3000


