version: "3.6"

services:
  mongodb:
    image: "mongo"
    ports:
      - 27017:27017
    volumes:
      - /var/log/mongo-data:/data/db

  server:
    build: 
      context: .
    depends_on:
      - mongodb
    environment:
      - DB
      - NODE_ENV
      - JWT_SECRET
    ports:
      - 5000:3000
    restart: unless-stopped
    volumes:
      - /var/log/mesto-server:/app/logs
